### PR TITLE
Added an option to wake a pony up when the system starts.

### PR DESCRIPTION
**Pull request by Svetomech**
Morning in Ponyville shimmers, morning in Ponyville shines!

### CODE REVIEW

**Comment by Svetomech** [comment]
Fixed now.

**Comment by Svetomech** [comment]
This should be all for now.

**Comment by Svetomech** [comment]
This should be all I guess...

**Comment by Svetomech** [comment]
Sorry this pull request is so messy - working with git in VS is evil.

**Comment by Svetomech** [comment]
This was a nasty one.

**Comment by Svetomech** [comment]
Really nasty one.

**Comment by Svetomech** [comment]
Anyone?

**Comment by bobmagicii** [comment]
just waiting to see when the chain of commits ends lol. then i'll reinstall visual studio (i just reinstalled windows last week) ;)

**Comment by Svetomech** [comment]
I have at least one else thing in mind, but it will wait till another pull request.

**Comment by bobmagicii** [comment]
alright i'll try and make time to reinstall VS tonight.

**Comment by Svetomech** [comment]
Were you not successful?

**Comment by bobmagicii** [comment]
god this is the slowest process, ever. 350mbit connection and it spends about 17 days downloading 10gb.

capture

**Comment by Svetomech** [comment]
I won't believe you if you say it's still downloading. Is it?

**Comment by Svetomech** [comment]
Okay then.

**Pull request closed without merging**
